services:
  reelfake_api_dev:
    image: reelfake/reelfake-api
    env_file: .env.dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reelfake-api
    ports:
      - 8000:8000
    networks:
      - reelfake-net

networks:
  reelfake_network:
    name: reelfake-net
    driver: bridge
